const fs = require('fs');
const path = require('path');

function initCommand() {
  const targetDir = process.cwd();
  const bddDocsDir = path.join(targetDir, 'gorkin');
  const featuresDir = path.join(targetDir, 'features');
  
  console.log(`[Gorkin] Initializing gorkin in ${targetDir}...`);
  
  // 1. Create gorkin directory if not exists
  if (!fs.existsSync(bddDocsDir)) {
    fs.mkdirSync(bddDocsDir, { recursive: true });
    console.log(`  [+] Created directory: ./gorkin`);
  }

  // 2. Create gorkin.config.js
  const configPath = path.join(bddDocsDir, 'gorkin.config.js');
  if (fs.existsSync(configPath)) {
    console.log(`  [~] Config file already exists, skipping: ./gorkin/gorkin.config.js`);
  } else {
    const configContent = `/** @type {import('gorkin/src/config/types').BddDocsConfig} */
const config = {
  // Directory of your .feature files (relative to this config file)
  featuresDir: '../features',

  // Directory of your Go modules (used to discover go.mod)
  // Tool will recursively search for tests inside these directories.
  modulesDir: ['../'],

  // Directory for isolated JSON reports generated by Ginkgo
  reportsDir: './.reports',

  // RegExp to match the tags linking Gherkin with Ginkgo.
  // The default pattern matches tags like @HELLO_001.
  tagPattern: /^[A-Z0-9]+_\\d{3}$/,

  // Site metadata
  title: 'My BDD Living Documentation',
  description: 'Living Documentation powered by Gorkin',
}

module.exports = config;
`;
    fs.writeFileSync(configPath, configContent);
    console.log(`  [+] Created config file: ./gorkin/gorkin.config.js`);
  }

  // 3. Create features directory and hello.feature
  if (!fs.existsSync(featuresDir)) {
    fs.mkdirSync(featuresDir, { recursive: true });
    console.log(`  [+] Created directory: ./features`);
  }
  
  const featurePath = path.join(featuresDir, 'hello.feature');
  if (fs.existsSync(featurePath)) {
    console.log(`  [~] Feature file already exists, skipping: ./features/hello.feature`);
  } else {
    const featureContent = `Feature: Hello World
  As a new user
  I want to see a working Gherkin scenario
  So that I can understand how Gorkin works

  @HELLO_001
  Scenario: Simple math
    Given I have a calculator
    When I add 2 and 2
    Then the result should be 4
`;
    fs.writeFileSync(featurePath, featureContent);
    console.log(`  [+] Created demo feature: ./features/hello.feature`);
  }

  // 4. Create hello_test.go
  const goTestPath = path.join(targetDir, 'hello_test.go');
  if (fs.existsSync(goTestPath)) {
    console.log(`  [~] Test file already exists, skipping: ./hello_test.go`);
  } else {
    const goTestContent = `package main_test

import (
\t"testing"

\t. "github.com/onsi/ginkgo/v2"
\t. "github.com/onsi/gomega"
)

func TestHello(t *testing.T) {
\tRegisterFailHandler(Fail)
\tRunSpecs(t, "Hello Suite")
}

var _ = Describe("Hello World", Label("HELLO_001"), func() {
\tIt("Simple math", func() {
\t\tExpect(2 + 2).To(Equal(4))
\t})
})
`;
    fs.writeFileSync(goTestPath, goTestContent);
    console.log(`  [+] Created demo test: ./hello_test.go`);
  }

  console.log('\\n[Gorkin] Initialization complete! 🎉');
  console.log('You can now start the living documentation server by running:');
  console.log('  npx gorkin dev');
}

module.exports = initCommand;
